### ISSUE TITLE
NRC data

### ISSUE THREAD

**Issue by diatomdaniel** [swulfing/STOICH.Aim1#3]
Has NRC data been cleaned yet? If not, shall I take this on @LinneaRock?

**Comment by LinneaRock** [comment]
Hey @diatomdaniel -- if you have the time that would be fantastic! I'm on vacation this week and haven't been able to look. Thank you so much.

**Comment by diatomdaniel** [comment]
@LinneaRock NRC has been cleaned and uploaded. Some irregularities with the data though; please look at the comments I added to the data management wiki
Thanks!
